### ISSUE TITLE
Issue loading UI since 3.09

### ISSUE THREAD

**Issue by luisfpsoares** [nilouco/dpAutoRigSystem#16]
Error: dpAutoRig UI window !!!
Exception: 'm153_piston'
Cannot load dpAutoRig UI window..., please try save the dpAutoRigSystem folder in MAYA_PATH directory and verify if you did not changed any file. 
dpAutoRigSystem loaded with success.

Windows 10; Maya 2020; update DPAutorig 3.09.01.
dpAutoRig is in the supposed directory and nothing has been changed.

**Comment by nilouco** [comment]
Hi Luis,

thanks for your issue report.
It happens when we try to AutoUpdate from menu using an older version like v3.07.08, sorry.
The problem was the older dpInstallUpdate didn't override dictionary json files.
Then the UI isn't able to load because any language was built in order to worked well.

I recommend download manually the last commit or the last release (v3.09 or newer) and replace the installed version in you computer.
So, we can be safe for the next updates incoming.

Let me know if it works well for you or if you have any problem, please.

Cheers,
Danilo.

**Comment by luisfpsoares** [comment]
It was during the AutoUpdate, yes. But I was coming from latest version before this.
This has solved my issue. Obrigado Danilo!
Just to clarify, if this happens to anyone else: Replacing the files was still not working. I had to delete the previous directory and paste the new one.

Keep up the incredible and unbelievable job, Danilo!
