### ISSUE TITLE
import pyside error.

### ISSUE THREAD

**Issue by GerrieWell** [nilouco/dpAutoRigSystem#4]
My machine : osX 10.11 +maya 2013
I was trying install follow this [Install · nilouco/dpAutoRigSystem Wiki](https://github.com/nilouco/dpAutoRigSystem/wiki/Install).

But occur error like this.

```
Error: importing python modules!!!
dlopen(/Applications/Autodesk/maya2013/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.6/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /Applications/Autodesk/maya2013/Maya.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.6/site-packages/PySide/QtCore.so
  Reason: image not found
```

BTW, my pySide and pyQt4 are copyed from pip and brew install.
Is there any wrong?

**Comment by sbourgoing** [comment]
Hi Gerrie,

I don't have any OsX machine to reproduce your problem, but from what I've found, it seem that your pyside installer is broken.

Look at this page of info and let me know if it help !

http://stackoverflow.com/questions/25656307/pyside-qt-import-error

**Comment by mgidney** [comment]
I think its a bigger issue than this - Qt5 and Qt4 issue

**Comment by mgidney** [comment]
scratch that - kind of - it is a pyside2 issue - perhaps you can move toward using pyside2 and shiboken2?  its a maya 2017 thing no?

**Comment by sbourgoing** [comment]
Hello there !

Been a while since someone comment on dpAutoRig. I am not really putting any more time in this project since I don't really have time for it and also because I now use another rigging system.

From the first comment, the problem was not a Maya 2017 problems, since it happen on maya 2013.

But concerning problem between Pyside and Pyside2 in the different maya version, the best solution I have seen is to use Qt.py(https://github.com/mottosso/Qt.py) which allow to support the two different version of PySide and consequently being able to support Maya using PySide and Maya 2017 which use PySide2.

Hope it helps !

**Comment by nilouco** [comment]
Thank you very much guys!
I followed the concern by sbourgoing and I think it is working well in Maya 2017 and older versions too.
Thanks! Cheers, Danilo.
